scality/runner-manager

.github/workflows/release.yml

github.repository variable also contain the org name and not only the repo name

Fix docker registry url for registry.scality.com

---

charts/openstack-actions-runner/templates/deployment.yaml

Currently if we only make some changes on the config, the service does not restart and the new configuration are not took into account.
This pr add a little helm trick to ensure that we are always in sync with the settings.

Restart service on config change

---

templates/init_runner_script.sh

Docker dns setting was set as:
```
{
dns: [10.100.1.1, 10.100.1.2, 10.100.1.3]
}
```
making it an invalid json file

RELENG-5806 invalid json for docker daemon settings

---

Dockerfile
srcs/runners_manager/vm_creation/aws/AwsManager.py

Over the past few weeks, we've encountered an issue with the AWS runner-manager. Specifically, in the code of the `runner-manager` repository, we were unable to dynamically set the tags and had to hardcode them in the code. As a result, we are working to address this issue with this pull request.

[PTFE-105] 🐛 Fix AWS runner-manager tags problem in the conf file

---

srcs/runners_manager/runner/RunnerManager.py

When a new runner is required the function need_new_runner is stucked in a while loop until a runner is created. We noticed if the max is reached we get a lot of error message. So i use and if condition instead of while. In any case the manage_runners function that calls the need_runner function is ran every 2 mins so this would atleast reduce the number of log entries

PTFE-456: break loop when demanding new runner

---

srcs/runners_manager/runner/RunnerManager.py
srcs/runners_manager/vm_creation/gcloud/GcloudManager.py

Spot instances are still being spawn. This is because the check that obtains the value of the spot key does not work properly. It always returns true. This is a fix.

PTFE-610: bugfix rollback spot instances

---

.trunk/trunk.yaml

After failing to configure checkov's execution on GitHub Actions workflows only and other configuration needed. Deactivating it for now.

PTFE-711 disable chekcov

---

.devcontainer/devcontainer.json
.github/dependabot.yaml
.github/workflows/codeql.yaml
.github/workflows/test-deployment.yaml
manifests/base/redis/kustomization.yaml
manifests/base/redis/statefulset.yaml
manifests/base/runner-manager/main/deployment.yaml

Deployment tests failing with the following error:
```shell
configmap/redis-config-6tc26t8d82 created
service/redis created
service/runner-manager created
deployment.apps/runner-manager-worker created
statefulset.apps/redis created
Error from server (BadRequest): error when creating "STDIN": Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal number into Go struct field Container.spec.template.spec.containers.args of type string
```
Error due to setting `- 0.0.0.0` instead of `- '0.0.0.0'` as args on the container. Fixed it by removing the args/command and using the default values to run the runner-manager API.
Couple of extra changes made along the way while debugging this issue:
- Changed the kustomize image override.
- Added kubernetes vscode extension. …

Fix deployment tests BadRequest failure 

---

runner_manager/auth.py
runner_manager/main.py
runner_manager/models/settings.py

As discussed we are going to handle the healthcheck authorization through the ingress configuration, not exposing the endpoint to the outside world.

Remove trusted host middleware

---

poetry.lock
pyproject.toml

As we are missing support of some types: more precisely workflow job steps with `queued` as status which are not yet introduced in the latest release but available in the master branch of the project, we are temporarily adding the project through the git repository while we wait for the next release.

PTFE-754 adding githukit through git repo to get latest release

---

images/runner/entrypoint.sh
runner_manager/backend/gcloud.py
runner_manager/bin/startup.sh
runner_manager/jobs/workflow_job.py
runner_manager/models/backend.py
runner_manager/models/runner.py
runner_manager/models/runner_group.py
tests/unit/conftest.py
tests/unit/jobs/test_healthchecks.py
tests/unit/jobs/test_startup.py
tests/unit/jobs/test_workflow_job.py
tests/unit/models/test_runner_group.py

The healthcheck function would check if runner.id is defined in order to retrieve its state from github.
The problem with that is that unless the runner has started a job, we would never retrieve its id, so idle runner would never be able to get an updated status and be forever considered as offline by the runner manager.
To fix this issue, we are using another endpoint to create the registration token for runners, which allow us to specify the full runner configuration as well as retrieve the id that will be given.
Thanks to this change we will always have an `runner.id` to work with.

healthcheck runner checkup

---

runner_manager/models/runner.py
runner_manager/models/runner_group.py
tests/unit/conftest.py
tests/unit/jobs/test_healthchecks.py
tests/unit/models/test_runner.py
tests/unit/models/test_runner_group.py

Now generating datetime with utc as timezone.
Using `datetime.now(timezone.utc)` instead of `datetime.utcnow()` as with `utcnow` the `tzinfo` remains `None` and is not able to compare datetimes that comes from GitHub's API which explicitly contain offset information.

PTFE-864 Ensure datetimes are compared with timezones

---

runner_manager/models/backend.py
tests/unit/backend/test_base.py
tests/unit/models/test_settings.py

var of type `SecretStr` are being stored as `*****` in redis with [redis-om](https://github.com/redis/redis-om-python). Leaving us unable to retrieve the proper password when the group is retrieved from the database and not from the settings configuration in the code.
Now defining the var as `str` until we find a proper solution to the issue.

PTFE-742 cannot store redhat password as secretstr

---

poetry.lock
pyproject.toml
runner_manager/backend/aws.py
runner_manager/backend/base.py
runner_manager/backend/docker.py
runner_manager/backend/gcloud.py
runner_manager/clients/github.py
runner_manager/dependencies.py
runner_manager/jobs/workflow_job.py
runner_manager/models/runner.py
runner_manager/models/runner_group.py
runner_manager/models/settings.py
runner_manager/models/webhook.py
runner_manager/routers/webhook.py
tests/api/test_webhook_router.py
tests/conftest.py
tests/strategies.py
tests/unit/backend/test_gcp.py
tests/unit/jobs/test_workflow_job.py
tests/unit/models/test_runner.py
tests/unit/models/test_runner_group.py

GitHub most likely made some updates and small tweaks to the data it sends with webhook, and the runner-manager is currently raising some 422 errors when receiving some of them.
Updating githubkit to the latest version available to benefit from the latest changes/updates within GitHub's API.

PTFE-1575 Upgrade githubkit to latest version

---

runner_manager/jobs/workflow_job.py

Following #555, an assertion error was occuring due to the assumption that both the `created_at` and `started_at` fields in the `workflow_job` webhooks were `datetime` instead of `str`.  This, following the pattern in #555, converts the `str` value of the webhook into `datetime` before the assertion.

fix assertion error due to incorrect type assumption in webhook timestamp

---

.devcontainer/devcontainer.json

Use the `--with` option from [poetry install](https://python-poetry.org/docs/cli/#install) to install dependency groups instead of `--group`.
This fixes an error shown on VSCode startup when using the devcontainer:
```
Running the postCreateCommand from devcontainer.json...
[98026 ms] Start: Run in container: /bin/sh -c poetry install --no-interaction --no-ansi --no-root --group=docs --group=dev
Creating virtualenv runner-manager in /workspaces/runner-manager/.venv
The option "--group" does not exist
[101878 ms] postCreateCommand failed with exit code 1. Skipping any further user-provided commands.
Done. Press any key to close the terminal.
```

fix(poetry): error in devcontainer command

---

mkdocs.yml

Address deprecation warning when running `poetry run mkdocs build --strict`.
From the upstream [mkdocs-material emoji documentation](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/?h=material+emoji#configuration):
```
- pymdownx.emoji:
emoji_index: !!python/name:material.extensions.emoji.twemoji
emoji_generator: !!python/name:material.extensions.emoji.to_svg
```

fix(docs): deprecation warning in mkdocs

---

runner_manager/models/backend.py
tests/unit/backend/test_aws.py

Currently there is no way of assigning IAM roles to runner instances at creation time. This PR adds an additional field in the AWS backend which creates EC2 instances with the specified `IamInstanceProfile`, configurable by the `iam_instance_profile_arn` field in the `runner-manager.yaml` config.
This implementation only accepts instances profiles by their ARN and not by their name to keep the implementation as simple as possible.

aws: add support for instance profiles

---

runner_manager/models/runner_group.py
tests/unit/jobs/test_healthchecks.py

Reverting the backend leak check due to it killing healthy runners.

Revert backend leak check

---

runner_manager/routers/webhook.py
tests/api/test_webhook_router.py

Fixes an issue which allowed webhooks to be processed with an incorrect webhook secret. 
This adds a case to return a `401` when the `verify` function returns false. The `verify` function also always returns false as it is being passed in JSON from a `WorkflowJob` webhook object instead of the request body (which is how GitHub generates it's signitures) meaning the signatures will never match (see https://github.com/yanyongyu/githubkit?tab=readme-ov-file#webhook-verification).

webhook: fix non-matching webhook secrets not being rejected

---

manifests/base/runner-manager/redis/statefulset.yaml
runner_manager/jobs/startup.py
runner_manager/models/settings.py
runner_manager/routers/_health.py
tests/api/test_health.py

If the redis instance happens to reboot during the runtime of the runner manager, redis will need for the `Migrator().run()` function to run to re-create the indexes. Otherwise we will face an interruption of service with the error:
```shell
redis.exceptions.ResponseError: runner-manager:runner_manager.models.runner_group.RunnerGroup:index: no such index
```
The following actions were taken in the code:
- Reduce the index interval from one hour to 15 minutes.
- Add more context to the indexing function, with this information.
- When failing to contact the redis instance, on the healtcheck, schedule a index run for a more dynamic self-healing approach.

PTFE-1798 handling errors of no such index

---

runner_manager/routers/runner_groups.py
tests/api/test_runner_groups_router.py

Adds an endpoint at `/groups/{name}/list` to list the runners in each runner group .
Relates to #625

api: add endpoint to list runners

---

.github/dependabot.yaml

* re-configure dependabot groups for pip
* Add support for devcontainers

Update and review of dependabot config

---

runner_manager/models/runner_group.py

- The config params loaded in [settings](https://github.com/scality/runner-manager/blob/main/runner_manager/models/settings.py#L33) maps to the [BaseRunnerGroup](https://github.com/scality/runner-manager/blob/main/runner_manager/models/runner_group.py#L32) . 
- Added `os` and `arch` params to the BaseRunnerGroup in order to configure them through the config yaml.
- This is required for filtering the [download_url](https://github.com/scality/runner-manager/blob/main/runner_manager/models/runner_group.py#L130)

Expose os and arch param for BaseRunnerGroup

---

.github/workflows/build.yaml
.github/workflows/test-deployment.yaml

Ensure the workflows `test-deployment.yaml` and `build.yaml` work on a forked PR.

Provide better experience for forked PRs

---

runner_manager/bin/startup.sh

A softer approach to the job started hook checks that runs systematically. 
To avoid a situation where those hook might do more harm than good, if they continuously fail after a certain amount of tries, release the runner and let it do its thing.

Do not block job from running on runner hooks

---

runner_manager/models/backend.py
tests/unit/backend/test_aws.py

At the moment it is not possible to allow EC2 instances to access their metadata tags when they are created. The changes in this PR adds a field within the AWS backend to create EC2 instances, specifying if the `InstanceMetadataTags` option in `InstanceMetadataOptions` is `disabled` (the default) or `enabled`. This option can be configured with the `instance_metadata_tags` option in `runner-manager.yaml`

aws: allow EC2 instance access to metadata tags

---

runner_manager/bin/startup.sh

The `job_started_script` and `job_completed_script` pre-emptively expand any shell parameters defined in them, resulting in them being expanded when the `/opt/runner/job_started_script.sh` and `/opt/runner/job_completed_script.sh` files are created and not at runtime of the job.
Instructing the heredoc document to skip expanding any shell parameters gives the expected functionality without having to escape them in the config file.

fix: job hook scripts pre-emptively expands shell parameters

---

runner_manager/backend/openstack.py

Filter openstack runners by the metadata tags

openstack: filter using metadata

---

runner_manager/backend/aws.py
runner_manager/models/backend.py
tests/unit/backend/test_aws.py

Update the AWS backend (and instance config) to add the ability to run instance on a set of subnets (and
so availability zone).
The main use-case for this is to allow instance to come up in multiple availability zones. A user would create one (or more) subnets in an availability zone and the list the subnets in the `subnet_configs` section. This has two main advantages:
- There is some crude load balancing (subnets are picked at random from the list)
- If an instance fails to start we can retry in another subnet. This will help in cases where an AZ has been starved of all the instance and instance not longer start.
To support this (without breaking existing configs) I added a new `subnet_configs` section to the instance config. This is mutually exclusive to the existing `subnet_id` …

aws-backend: add support for running instances on multiple subnets

---

runner_manager/bin/startup.sh

Since 18/06/2025 ubuntu runner on Jammy can't launch there systemd service because de base64 $JIT_CONFIG is to large for systemd.
Here we push the base64 in an env var which will be use by the command line.
This type of systemd service has been test both on ubuntu22.04 and ubuntu24

(PTFE-2499) Add variable to deploy service systemd

---

runner_manager/bin/startup.sh

Escape $ to avoid empty variable pass to systemd

(PTFE-2499) Escape the variable JIT_BASE64 to avoid being empty
